export const applicantsSchemaColumnNames = [
  "COAP",
  "AppNo",

  "Email",
  "FullName",
  "MaxGateScore",
  "Adm",
  "Pwd",
  "Ews",
  "Gender",
  "Category",
  "GATE21RollNo",
  "GATE21Rank",
  "GATE21Score",
  "GATE21Disc",
  "GATE23RollNo",
  "GATE23Rank",
  "GATE23Score",
  "GATE23Disc",
  "GATE22RollNo",
  "GATE22Rank",
  "GATE22Score",
  "GATE22Disc",
  "HSSCboard",
  "HSSCdate",
  "HSSCper",
  "SSCboard",
  "SSCdate",
  "SSCper",
  "DegreeQual",
  "DegreePassingDate",
  "DegreeBranch",
  "DegreeOtherBranch",
  "DegreeInstitute",
  "DegreeCGPA7thSem",
  "DegreeCGPA8thSem",
  "DegreePer7thSem",
  "DegreePer8thSem",
];
export const applicantsSchemaColumnNamesJson = {
  COAP: [],
  AppNo: [],

  Email: [],
  FullName: [],
  MaxGateScore: [],
  Adm: [],
  Pwd: [],
  Ews: [],
  Gender: [],
  Category: [],
  GATE21RollNo: [],
  GATE21Rank: [],
  GATE21Score: [],
  GATE21Disc: [],
  GATE23RollNo: [],
  GATE23Rank: [],
  GATE23Score: [],
  GATE23Disc: [],
  GATE22RollNo: [],
  GATE22Rank: [],
  GATE22Score: [],
  GATE22Disc: [],
  HSSCboard: [],
  HSSCdate: [],
  HSSCper: [],
  SSCboard: [],
  SSCdate: [],
  SSCper: [],
  DegreeQual: [],
  DegreePassingDate: [],
  DegreeBranch: [],
  DegreeOtherBranch: [],
  DegreeInstitute: [],
  DegreeCGPA7thSem: [],
  DegreeCGPA8thSem: [],
  DegreePer7thSem: [],
  DegreePer8thSem: [],
};
