var applicantsSchema=`(
    COAP VARCHAR(200) PRIMARY KEY,
    AppNo VARCHAR(200) NOT NULL UNIQUE, 
    Email VARCHAR(500) NOT NULL UNIQUE,
    FullName text NOT NULL,
    MaxGateScore float(24) NOT NULL,
    Adm text NOT NULL,
    Pwd text NOT NULL,
    Ews text NOT NULL,
    Gender text NOT NULL,
    Category text NOT NULL,
    GATE21RollNo text,
    GATE21Rank integer,
    GATE21Score float(24),
    GATE21Disc text, 
    GATE23RollNo text, 
    GATE23Rank integer,
    GATE23Score float(24),
    GATE23Disc text, 
    GATE22RollNo text, 
    GATE22Rank integer,
    GATE22Score float(24),
    GATE22Disc text, 
    HSSCboard text,
    HSSCdate text, 
    HSSCper float(24), 
    SSCboard text, 
    SSCdate text, 
    SSCper float(24),
    DegreeQual text, 
    DegreePassingDate text,
    DegreeBranch text,
    DegreeOtherBranch text,
    DegreeInstitute text,
    DegreeCGPA7thSem float(24),
    DegreeCGPA8thSem float(24), 
    DegreePer7thSem float(24),
    DegreePer8thSem float(24)
)
`
applicantsSchemaColumnNames=
[
    "COAP",
    "AppNo" , 
    "Email",
    "FullName",
    "MaxGateScore",
    "Adm",
    "Pwd",
    "Ews",
    "Gender",
    "Category",
    "GATE21RollNo" ,
    "GATE21Rank" ,
    "GATE21Score" ,
    "GATE21Disc" , 
    "GATE23RollNo" , 
    "GATE23Rank" ,
    "GATE23Score" ,
    "GATE23Disc" , 
    "GATE22RollNo" , 
    "GATE22Rank" ,
    "GATE22Score" ,
    "GATE22Disc" , 
    "HSSCboard" ,
    "HSSCdate" , 
    "HSSCper", 
    "SSCboard" , 
    "SSCdate" , 
    "SSCper" ,
    "DegreeQual" , 
    "DegreePassingDate" ,
    "DegreeBranch" ,
    "DegreeOtherBranch" ,
    "DegreeInstitute" ,
    "DegreeCGPA7thSem" ,
    "DegreeCGPA8thSem" , 
    "DegreePer7thSem" ,
    "DegreePer8thSem" 
]
module.exports={applicantsSchema,applicantsSchemaColumnNames};